# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigIntegerField(max_length=20, primary_key=True, serialize=False)),
                ('gmt_create', models.DateTimeField(default=b'Thu Aug 10 22:26:37 2017')),
                ('gmt_modified', models.DateTimeField(default=b'Thu Aug 10 22:26:37 2017')),
                ('index', models.IntegerField(max_length=8)),
                ('img', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='gmt_create',
            field=models.DateTimeField(default=b'Thu Aug 10 22:26:37 2017'),
        ),
        migrations.AddField(
            model_name='app',
            name='gmt_modified',
            field=models.DateTimeField(default=b'Thu Aug 10 22:26:37 2017'),
        ),
    ]
